version: '3'

services:
  rsyncarr:
    build: .
    container_name: rsyncarr
    environment:
      RADARR_API_URL: http://server.ip.address:7878
      RADARR_API_KEY: YOUR-API-KEY
      SONARR_API_URL: http://server.ip.address:8989
      SONARR_API_KEY: YOUR-API-KEY
#      LIDARR_API_URL: {LIDARR_API_URL}
#      LIDARR_API_KEY: {LIDARR_API_KEY}
#      READARR_API_URL: {READARR_API_URL}
#      READARR_API_KEY: {READARR_API_KEY}
    volumes:
      - /mnt/seedbox/files/downloads:/seedbox
      - /mnt/storage/local:/data
      - /mnt/seedbox/.config/transmission-daemon/torrents:/torrents
      - /mnt/storage/local/watch:/watch
      - /mnt/docker/rsyncarr:/app
    network_mode: host


